FROM alpine

# if the command is to be run internal to the container, the label immediately
# following 'health' must be 'in'
LABEL ogre.health.in.unique.check.one="ping -c 1 127.0.0.1"

# if the command is to be run external to the container, the label immediately
# following 'health' must be 'ex' - note that if you are not running ogre on
# the host, i.e. running in a container, the ogre container must also be part
# of any custom network configurations you may have, if any, in order to reach
# a container.  
LABEL ogre.health.ex.unique.check.two="nc -vz 172.17.0.3 8000"

# if neither 'in' nor 'ex' is present, ogre will attempt to make the check from
# inside the container
LABEL ogre.health.unique.check.three="echo inside"

# to enable the health checks to be reported to prometheus use the label
# LABEL ogre.format.backend.prometheus="true"

# Currently the below is not supported but may be offered as another unique label
# in a future iteration, for now use the ogre config file
# LABEL ogre.format.backend.prometheus.metric="metric name"

# Currently the below is not supported but may be offered as another unique label
# in a future iteration, for now use the ogre config file
# LABEL ogre.format.backend.prometheus.label="label name"

# enable the statsd backend
# LABEL ogre.format.backend.statsd="true"

# enable a generic http backend which can accept json via a POST request
# LABEL ogre.format.backend.http="true"

# if you could like to collect the output of healthchecks and send that value you
# can format the health checks like below
#
# (collect output from the command as a string)
# LABEL ogre.format.health.output.type="string"
#
# (collect output from the command as an int)
# LABEL ogre.format.health.output.type="int"
#
# (collect output from the command as a float)
# LABEL ogre.format.health.output.type="float"

# inform ogre to collect the exit code of health checks (default)
LABEL ogre.format.health.output.result="exit"

# inform ogre to collect the return of the command itself, i.e. if you had a
# check like `ls /proc | wc -l` 
# LABEL ogre.format.health.output.result="return"

# the interval at which checks should be run
LABEL ogre.format.health.interval="5s"

ENTRYPOINT ["nc", "-lke", "127.0.0.1", "8000"]
